services:
  postgres:
    image: postgres:17-alpine
    container_name: books_db_container

    environment:
      POSTGRES_DB: book_review_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d book_review_db"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    